name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Cambia a la rama que desees

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Cambia a tu versión de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run your app (adjust as needed)
        run: |
          # Aquí puedes agregar comandos para ejecutar tu app, si es necesario.
          echo "Your app is ready to be deployed"
